spring.application.name=backend
spring.docker.compose.file=../../../compose.yaml

# Close the DB connection after each request (recommended for REST APIs)
spring.jpa.open-in-view=false

# Flyway creates tables, Hibernate only checks they match your Java classes
spring.jpa.hibernate.ddl-auto=validate